/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.autoplus.frame;

import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.awt.Toolkit;
import java.beans.PropertyVetoException;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;




/**
 *
 * @author malek
 */
public class AcceulGui extends javax.swing.JFrame {

    /**
     * Creates new form AcceulGui
     */
    public AcceulGui() {
        initComponents();
        dateCourante();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("insurance-icon-car-share-icon-vehicle-sedan-transport-automobile-repair-shop-electric-car-png-clipart.png")));
    }
    public void dateCourante(){
        Thread clock=new Thread(){
            public void run(){
                for(;;){
                    Calendar Cal=new GregorianCalendar();
                    int second=Cal.get(Calendar.SECOND);
                    int minute=Cal.get(Calendar.MINUTE);
                    int hour= Cal.get(Calendar.HOUR);
                    int PM_AM= Cal.get(Calendar.AM_PM);
                    String pa;
                    if(PM_AM==1){
                        pa="PM";
                    }else{
                        pa="AM";
                    }
                   
                    lbDate.setText("Heure:"+hour+":"+(minute)+":"+second+" "+pa);
                    String filename="C:\\Users\\malek\\Desktop\\DS-digital\\DS-DIGI.TTF";
                    try {
                        Font font = Font.createFont(Font.TRUETYPE_FONT, new File(filename));
                        font = font.deriveFont(Font.BOLD,24);
                        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
                        ge.registerFont(font);
                        lbDate.setFont(font);
                    } catch (FontFormatException ex) {
                        Logger.getLogger(AcceulGui.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IOException ex) {
                        Logger.getLogger(AcceulGui.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                    int mois=Cal.get(Calendar.MONTH);
                    int annee=Cal.get(Calendar.YEAR);
                    int jour=Cal.get(Calendar.DAY_OF_MONTH);
                    lbDate1.setText("Date:"+jour+"/"+(mois+1)+"/"+annee);
                    try{
                      sleep(1000);  
                      
                    }catch(InterruptedException ex){
                        Logger.getLogger(Calendar.class.getName()).log(Level.SEVERE,null,ex);
                    }
                    String filename1="C:\\Users\\malek\\Desktop\\24_led\\24_LED.ttf";
                    Font font;
                    try {
                        font = Font.createFont(Font.TRUETYPE_FONT, new File(filename1));
                         font = font.deriveFont(Font.BOLD,24);
                        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
                        ge.registerFont(font);
                        lbDate1.setFont(font);
                    } catch (FontFormatException ex) {
                        Logger.getLogger(AcceulGui.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IOException ex) {
                        Logger.getLogger(AcceulGui.class.getName()).log(Level.SEVERE, null, ex);
                    }
                       
                }
            }
        };
        clock.start();
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbDate = new javax.swing.JLabel();
        lbDate1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Acceuil = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Desk = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 380));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        lbDate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbDate.setForeground(new java.awt.Color(51, 51, 255));
        getContentPane().add(lbDate);
        lbDate.setBounds(1150, 20, 200, 20);

        lbDate1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbDate1.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lbDate1);
        lbDate1.setBounds(1150, 0, 200, 20);

        jLabel3.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 204));
        jLabel3.setText("Auto MAX");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 0, 90, 20);

        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Gestion Auto Ecole TN");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 20, 120, 14);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/autoplus/images/menu1.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-4, 0, 1370, 40);

        Acceuil.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Acceuil.setForeground(new java.awt.Color(255, 255, 255));
        Acceuil.setText("Acceuil");
        Acceuil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AcceuilMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AcceuilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AcceuilMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AcceuilMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                AcceuilMouseReleased(evt);
            }
        });
        getContentPane().add(Acceuil);
        Acceuil.setBounds(10, 40, 50, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/autoplus/images/menu2222.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 40, 1366, 20);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/autoplus/images/1455.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(30, 90, 110, 70);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/autoplus/images/formation.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 180, 110, 70);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/autoplus/images/Examen.png"))); // NOI18N
        getContentPane().add(jButton3);
        jButton3.setBounds(30, 270, 110, 70);

        Desk.setBackground(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout DeskLayout = new javax.swing.GroupLayout(Desk);
        Desk.setLayout(DeskLayout);
        DeskLayout.setHorizontalGroup(
            DeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
        );
        DeskLayout.setVerticalGroup(
            DeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        getContentPane().add(Desk);
        Desk.setBounds(150, 90, 920, 420);

        setSize(new java.awt.Dimension(1382, 759));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.Desk.removeAll();
        this.Desk.repaint();
        List_des_candidats lc = new List_des_candidats();
        this.Desk.add(lc);
        try {
            lc.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(AcceulGui.class.getName()).log(Level.SEVERE, null, ex);
        }
        lc.show();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.Desk.removeAll();
        this.Desk.repaint();
        Formation fr = new Formation();
        this.Desk.add(fr);
        try {
            fr.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(AcceulGui.class.getName()).log(Level.SEVERE, null, ex);
        }
        fr.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.Desk.removeAll();
        this.Desk.repaint();
        Notes nt = new Notes();
        this.Desk.add(nt);
        try{
         nt.setMaximum(true);
        }catch(Exception e){
           Logger.getLogger(AcceulGui.class.getName()).log(Level.SEVERE,null,evt);
        }
        nt.show();
    }//GEN-LAST:event_formWindowOpened

    private void AcceuilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AcceuilMouseClicked
         this.Desk.removeAll();
        this.Desk.repaint();
        Notes nt = new Notes();
        this.Desk.add(nt);
        try{
         nt.setMaximum(true);
        }catch(Exception e){
           Logger.getLogger(AcceulGui.class.getName()).log(Level.SEVERE,null,evt);
        }
        nt.show();
        
    }//GEN-LAST:event_AcceuilMouseClicked

    private void AcceuilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AcceuilMouseEntered
        Acceuil.setForeground(Color.red);
    }//GEN-LAST:event_AcceuilMouseEntered

    private void AcceuilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AcceuilMouseExited
        Acceuil.setForeground(Color.white);
    }//GEN-LAST:event_AcceuilMouseExited

    private void AcceuilMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AcceuilMousePressed
        Acceuil.setForeground(Color.white);
    }//GEN-LAST:event_AcceuilMousePressed

    private void AcceuilMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AcceuilMouseReleased
        Acceuil.setForeground(Color.red);
    }//GEN-LAST:event_AcceuilMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
       try {
    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Windows".equals(info.getName())) {
            javax.swing.UIManager.setLookAndFeel(info.getClassName());
            break;
        }
    }
} catch (ClassNotFoundException ex) {
    java.util.logging.Logger.getLogger(AcceulGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
} catch (InstantiationException ex) {
    java.util.logging.Logger.getLogger(AcceulGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
} catch (IllegalAccessException ex) {
    java.util.logging.Logger.getLogger(AcceulGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
} catch (javax.swing.UnsupportedLookAndFeelException ex) {
    java.util.logging.Logger.getLogger(AcceulGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
}
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcceulGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcceulGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcceulGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcceulGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AcceulGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Acceuil;
    private javax.swing.JDesktopPane Desk;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbDate;
    private javax.swing.JLabel lbDate1;
    // End of variables declaration//GEN-END:variables
}
