/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.autoplus.frame;
import com.sun.org.apache.xerces.internal.util.MessageFormatter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.Locale;
import java.util.MissingResourceException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.JTable;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import static javax.swing.text.StyleConstants.setIcon;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author malek
 */
public class List_des_candidats extends javax.swing.JInternalFrame {
    Connection con=null;
    ResultSet rs=null;
    PreparedStatement ps=null;
    static String test;
    static String te;
    public ImageIcon Format=null;
    /**
     * Creates new form List_des_candidats
     */
    public List_des_candidats() {
        con=ConnexionBd.Connexion();
        initComponents();
        Affichage();
    }
    public String re(){
        return te;
    }
 
    //display table 
    public void Affichage(){
        try{
            String requete="select cin as 'CIN',nomc as 'NOM',prenomc as 'PRENOM',date_naissance as 'Date de Naissance',age as 'Age',sexe as 'Sexe',gsm as 'GSM',email as 'Email', date_inscription as 'Date d inscription',image as 'photo' from candidat_table";
            ps=con.prepareStatement(requete);
            rs=ps.executeQuery();
            Table.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception ex){
            System.out.println(ex);
        }
    }
    public void Deplace(){
        try{
           int row = Table.getSelectedRow();
           this.test=(Table.getModel().getValueAt(row,0).toString());
           String requet="Select * from candidat_table where cin = '"+test+"'";
           ps=con.prepareStatement(requet);
           rs=ps.executeQuery();
           if(rs.next()){
               String t1=rs.getString("cin");
               txtCin.setText(t1);
               String t2=rs.getString("nomc");
               txtNom.setText(t2);
               String t3=rs.getString("prenomc");
               txtPrenom.setText(t3);
               String t4=rs.getString("date_naissance");
               txtDateNais.setText(t4);
               String t5=rs.getString("age");
               txtAge.setText(t5);
               String t6=rs.getString("sexe");
               txtSexe.setText(t6);
               String t7=rs.getString("gsm");
               txtGsm.setText(t7);
               String t8=rs.getString("email");
               txtEmail.setText(t8);
               byte[]imagedata=rs.getBytes("image");
               Format = new ImageIcon(imagedata);
               image.setIcon(Format);
           }
        }catch(Exception ex){
            System.out.println(ex);
        }    
    }
    public String getTableResult(){
        return test;
    }
    void remove_title_bar(){
        putClientProperty("List_des_candidats.isPalette",true);
        getRootPane().setWindowDecorationStyle(JRootPane.NONE);
        ((BasicInternalFrameUI)this.getUI()).setNorthPane(null);
        this.setBorder(null);
    }
    public void Clear(){
        txtCin.setText("");
        txtNom.setText("");
        txtPrenom.setText("");
        txtDateNais.setText("");
        txtAge.setText("");
        txtSexe.setText("");
        txtGsm.setText("");
        txtEmail.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable() {
            public boolean isCellEditable(int d,int c){
                return false;
            }
        };
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCin = new javax.swing.JLabel();
        txtNom = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAge = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtGsm = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtSexe = new javax.swing.JLabel();
        txtPrenom = new javax.swing.JLabel();
        txtDateNais = new javax.swing.JLabel();
        txtEmail = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnModify = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        txtRechercher = new javax.swing.JTextField();
        btnRechercher = new javax.swing.JButton();
        btnUpdRech = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        image = new javax.swing.JLabel();

        setBorder(null);
        setTitle("Listes");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/autoplus/images/menu candidat.png"))); // NOI18N

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/autoplus/images/ajouter.png"))); // NOI18N
        btnAdd.setContentAreaFilled(false);
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.setFocusCycleRoot(true);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TableMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Information Candidat"));

        jLabel1.setText("Cin");

        jLabel4.setText("Nom");

        jLabel6.setText("Age");

        jLabel3.setText("Prenom");

        txtCin.setForeground(new java.awt.Color(0, 51, 153));

        txtNom.setForeground(new java.awt.Color(0, 51, 153));

        jLabel5.setText("Date de Naissance");

        txtAge.setForeground(new java.awt.Color(0, 51, 153));

        jLabel8.setText("GSM");

        txtGsm.setForeground(new java.awt.Color(0, 51, 153));

        jLabel7.setText("Sexe");

        txtSexe.setForeground(new java.awt.Color(0, 51, 153));

        txtPrenom.setForeground(new java.awt.Color(0, 51, 153));

        txtDateNais.setForeground(new java.awt.Color(0, 51, 153));

        txtEmail.setForeground(new java.awt.Color(0, 51, 153));

        jLabel9.setText("Email");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3))
                                .addGap(53, 53, 53))
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtGsm, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSexe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCin, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                    .addComponent(txtDateNais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPrenom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCin, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDateNais, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(txtSexe, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addComponent(txtGsm, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/autoplus/images/supprimer.png"))); // NOI18N
        btnDelete.setContentAreaFilled(false);
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.setFocusCycleRoot(true);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnModify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/autoplus/images/modifier.png"))); // NOI18N
        btnModify.setContentAreaFilled(false);
        btnModify.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModify.setFocusCycleRoot(true);
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });

        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/autoplus/images/imprimer.png"))); // NOI18N
        btnPrint.setContentAreaFilled(false);
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        txtRechercher.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRechercherKeyReleased(evt);
            }
        });

        btnRechercher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/autoplus/images/find_user.png"))); // NOI18N
        btnRechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRechercherActionPerformed(evt);
            }
        });

        btnUpdRech.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/autoplus/images/Update_user.png"))); // NOI18N
        btnUpdRech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdRechActionPerformed(evt);
            }
        });

        jLabel10.setText("Taper CIN ou Nom pour chercher:");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Photo Candidat"));

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/autoplus/images/img-landscape-photo-photography-picture-icon-12.png"))); // NOI18N
        image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnModify)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnUpdRech, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(jLabel10))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRechercher)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btnUpdRech, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRechercher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnModify, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPrint)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

        this.te="a";
        AjoutCandidat act= new AjoutCandidat();
        act.setVisible(true);
        act.ClearData();
    }//GEN-LAST:event_btnAddActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        Deplace();
        
    }//GEN-LAST:event_TableMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

      int row=Table.getSelectedRow();   // retourne la ligne séléctionnée


        if (row==-1)
        {
          JOptionPane.showMessageDialog(null, "Aucune ligne sélectionnée ");
          return ;
        }


        int p=JOptionPane.showConfirmDialog(null,"Voulez vous  vraiment  supprimer le candidat ?","supprimer", JOptionPane.YES_NO_CANCEL_OPTION);

    if(p==0)
    {
       try
        {
        String cin=(Table.getModel().getValueAt(row,0).toString());
        
        Class.forName("com.mysql.jdbc.Driver");// charger le driver ODBC

        Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost/auto_plus", "root", "");
        PreparedStatement pstmt3 = con.prepareStatement("delete from candidat_table  where cin=?");

        pstmt3.setString(1,cin);
        int result = pstmt3.executeUpdate();

        }catch(Exception e)
        {
            System.out.println(e);  
        }
    }
        Clear();
        btnDelete.setEnabled(false);
        btnModify.setEnabled(false);
        Affichage();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void TableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseReleased
        btnDelete.setEnabled(true);
        btnModify.setEnabled(true);
    }//GEN-LAST:event_TableMouseReleased

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        btnDelete.setEnabled(false);
        btnModify.setEnabled(false);
    }//GEN-LAST:event_formInternalFrameActivated

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        this.te ="ah";
        AjoutCandidat act= new AjoutCandidat();
        act.setVisible(true);
    }//GEN-LAST:event_btnModifyActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        MessageFormat header;
        header = new MessageFormat("Listes des candidats:");
        MessageFormat footer=new MessageFormat("page{0,number,integer})");
        try{
          Table.print(JTable.PrintMode.NORMAL,header,footer);
        }catch(java.awt.print.PrinterException e){
            System.err.format("Erreur d'impression",e.getMessage());
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnRechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechercherActionPerformed
        
//        try {
//            String requete= "select * from candidat_table where nomc=?";
//            ps=con.prepareStatement(requete);
//            ps.setString(1,txtRechercher.getText());
//            rs =ps.executeQuery();
//            Table.setModel(DbUtils.resultSetToTableModel(rs));
//        } catch (Exception ex) {
//            System.out.println(ex);
//        }
//           try {
//            String requete= "select * from candidat_table where nomc=?";
//            ps=con.prepareStatement(requete);
//            ps.setString(1,txtRechercher.getText());
//            rs =ps.executeQuery();
//            if(rs.next()){
//                String t1=rs.getString("cin");
//                txtCin.setText(t1);
//                String t2=rs.getString("nomc");
//                txtNom.setText(t2);
//                String t3=rs.getString("prenomc");
//                txtPrenom.setText(t3);
//                String t4=rs.getString("date_naissance");
//                txtDateNais.setText(t4);
//                String t5=rs.getString("age");
//                txtAge.setText(t5);
//                String t6=rs.getString("sexe");
//                txtSexe.setText(t6);
//                String t7=rs.getString("gsm");
//                txtGsm.setText(t7);
//                String t8=rs.getString("email");
//                txtEmail.setText(t8);
//            }
//                
//        } catch (Exception ex) {
//            System.out.println(ex);
//        }
    }//GEN-LAST:event_btnRechercherActionPerformed

    private void btnUpdRechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdRechActionPerformed
        Affichage();
        txtRechercher.setText("");
        Clear();
        btnDelete.setEnabled(false);
        btnModify.setEnabled(false);
        image.setIcon(null);
    }//GEN-LAST:event_btnUpdRechActionPerformed
    public void search(){
       try{
       String requete= "select * from candidat_table where nomc LIKE ?";
       ps=con.prepareStatement(requete);
       ps.setString(1,"%"+txtRechercher.getText()+"%");
       rs =ps.executeQuery();
       Table.setModel(DbUtils.resultSetToTableModel(rs));
       byte[]imagedata=rs.getBytes("image");
       ImageIcon Format = new ImageIcon(imagedata);
       image.setIcon(Format);
       } catch(Exception ex){
         System.out.println(ex);
       }
                  try {
            String requete= "select * from candidat_table where nomc LIKE ?";
            ps=con.prepareStatement(requete);
            ps.setString(1,"%"+txtRechercher.getText()+"%");
            rs =ps.executeQuery();
            if(rs.next()){
                String t1=rs.getString("cin");
                txtCin.setText(t1);
                String t2=rs.getString("nomc");
                txtNom.setText(t2);
                String t3=rs.getString("prenomc");
                txtPrenom.setText(t3);
                String t4=rs.getString("date_naissance");
                txtDateNais.setText(t4);
                String t5=rs.getString("age");
                txtAge.setText(t5);
                String t6=rs.getString("sexe");
                txtSexe.setText(t6);
                String t7=rs.getString("gsm");
                txtGsm.setText(t7);
                String t8=rs.getString("email");
                txtEmail.setText(t8);
                byte[]imagedata=rs.getBytes("image");
                ImageIcon Format = new ImageIcon(imagedata);
            }
                
        } catch (Exception ex) {
            System.out.println(ex);
        }
                             try {
            String requete= "select * from candidat_table where cin=?";
            ps=con.prepareStatement(requete);
            ps.setString(1,txtRechercher.getText());
            rs =ps.executeQuery();
            if(rs.next()){
                String t1=rs.getString("cin");
                txtCin.setText(t1);
                String t2=rs.getString("nomc");
                txtNom.setText(t2);
                String t3=rs.getString("prenomc");
                txtPrenom.setText(t3);
                String t4=rs.getString("date_naissance");
                txtDateNais.setText(t4);
                String t5=rs.getString("age");
                txtAge.setText(t5);
                String t6=rs.getString("sexe");
                txtSexe.setText(t6);
                String t7=rs.getString("gsm");
                txtGsm.setText(t7);
                String t8=rs.getString("email");
                txtEmail.setText(t8);
            }
                
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }
    private void txtRechercherKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRechercherKeyReleased
    search();
        
    }//GEN-LAST:event_txtRechercherKeyReleased

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameClosed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        this.Table.getTableHeader().setResizingAllowed(false);
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnModify;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnRechercher;
    private javax.swing.JButton btnUpdRech;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel txtAge;
    private javax.swing.JLabel txtCin;
    private javax.swing.JLabel txtDateNais;
    private javax.swing.JLabel txtEmail;
    private javax.swing.JLabel txtGsm;
    private javax.swing.JLabel txtNom;
    private javax.swing.JLabel txtPrenom;
    private javax.swing.JTextField txtRechercher;
    private javax.swing.JLabel txtSexe;
    // End of variables declaration//GEN-END:variables
}
